const FilmActionTypes = {
    GET_FILMS_START: 'GET_FILMS_START',
    GET_FILMS_SUCCESS: 'GET_FILMS_SUCCESS',
    GET_FILMS_FAIL: 'GET_FILMS_FAIL',

    SET_SELECTED_FILM: "SET_SELECTED_FILM",

    CLOSE_MODAL: "CLOSE_MODAL",

    SHOW_FILM_PREVIEW: "SHOW_FILM_PREVIEW",
    HIDE_FILM_PREVIEW: "HIDE_FILM_PREVIEW",

    SORT_FILMS: "SORT_FILMS",

    GET_CHARACTERS_START: "GET_CHARACTERS_START",
    GET_CHARACTERS_SUCCESS: "GET_CHARACTERS_SUCCESS",
    GET_CHARACTERS_FAIL: "GET_CHARACTERS_FAIL",

    GET_CHARACTER_BY_ID_START: "GET_CHARACTER_BY_ID_START",
    GET_CHARACTER_BY_ID_SUCCESS: "GET_CHARACTER_BY_ID_SUCCESS",
    GET_CHARACTER_BY_ID_FAIL: "GET_CHARACTER_BY_ID_FAIL",

    SET_CHARACTER: "SET_CHARACTER"
};

export default FilmActionTypes;